// Generated by Neo

#ifndef _AUDIO_RECORD_H_
#define _AUDIO_RECORD_H_

#include <jni.h>
#include <pthread.h>

#include <alu/jutils_types.h>

class AudioRecordBody;

class AudioRecord {
public:
	static AudioRecord* getInstance(JavaVM* vm);
	static void destory();

	bool start(SampleRate rate, ChannelConfig channel, PCMBit bit, int block,
			fetch cb);
	bool stop();

	bool set_volume(float gain);

private:
	AudioRecordBody* body_;

	~AudioRecord();

	DISALLOW_COPY_AND_ASSIGN(AudioRecord);

	DISALLOW_EMPTY_AND_POINTER(AudioRecord);
};

#endif /* _AUDIO_RECORD_H_ */
