// Generated by Neo

#ifndef _JNI_CALLBACKS_H
#define _JNI_CALLBACKS_H

#include <jni.h>

#include <JHDEC.h>
#include <net_interface.h>

#ifdef __cplusplus
extern "C" {
#endif

void ConnectChangeRTMP(int index, BYTE type, char* msg, int data);
void NormalDataRTMP(int index, BYTE type, BYTE* buf, int size, int ts);

void ConnectChange(int index, BYTE type, char* msg, int data);
void NormalData(int index, BYTE type, BYTE* buf, int size, int width,
		int height);
void CheckResult(int index, BYTE* buf, int size);
void ChatData(int index, BYTE type, BYTE* buf, int size);
void TextData(int index, BYTE type, BYTE* buf, int size);
void Download(int index, BYTE type, BYTE* buf, int size, int length);
void PlayData(int index, BYTE type, BYTE* buf, int size, int width, int height,
		int frame);

void onSearchLanServer(STLANSRESULT stLSResult);
int  onQueryDevice(STLANSRESULT* stLSResult);
void onBCSelfServer(unsigned char *pBuffer, int nSize, char chIP[16], int nPort,int nType) ;
int onOmxInfo(OMX_INFO * info);

#ifdef __cplusplus
}
#endif

#endif /* _JNI_CALLBACKS_H */
