// Generated by Neo

#ifndef _THREADS_H
#define _THREADS_H

#ifdef __cplusplus
extern "C" {
#endif

void* onStat(void* _stat);
void* onPlayVideo(void* _index);
void* onPlayAudio(void* _index);

void* onFoo(void* msg);
void* onBar(void* msg);

#ifdef __cplusplus
}
#endif

#endif /* _THREADS_H */
