// Generated by Neo

#ifndef _NPLAYER_DEFINES_H_
#define _NPLAYER_DEFINES_H_



#define ONLY_EMPTY_CONSTRUCTION(ClassName) \
    ClassName(const ClassName *);          \
    DISALLOW_COPY_AND_ASSIGN(ClassName)

#define ONLY_CUSTOM_CONSTRUCTION(ClassName) \
    DISALLOW_COPY_AND_ASSIGN(ClassName);    \
    DISALLOW_EMPTY_AND_POINTER(ClassName)

#define LOCATE __FUNCTION__, __LINE__
#define LOCATE_FULL __FILE__, __FUNCTION__, __LINE__



#ifdef _COCOA_PLATFORM_
#include <stdio.h>
#define LOGV(...) printf(__VA_ARGS__);
#define LOGD(...) printf(__VA_ARGS__);
#define LOGI(...) printf(__VA_ARGS__);
#define LOGW(...) printf(__VA_ARGS__);
#define LOGE(...) printf(__VA_ARGS__);
#endif

#endif /* _NPLAYER_DEFINES_H_ */
